format = """
[░▒▓](#a3aed2)\
[  ](bg:#a3aed2 fg:#090c0c)\
$sudo\
[](bg:#c9cbff fg:#a3aed2)\
$username\
$hostname\
$directory\
[](fg:#c9cbff bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#2e374c)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#2e374c bg:#6c7086)\
$time\
[](fg:#6c7086)\
\n$character\
"""

right_format="""
[](fg:#c9cbff bg:transparent)\
$status\
[](fg:#c9cbff bg:transparent) \
"""
add_newline = false


[username]
style_user = 'fg:#4c4f69 bg:#c9cbff'
style_root = 'black bold'
format = '[$user]($style)'
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue)[@$hostname:](fg:#4c4f69 bg:#c9cbff)'
trim_at = '.'
ssh_symbol = '🌐'
disabled = false

[sudo]
format ='[$symbol]($style)'
style = 'bg:#a3aed2 fg:#090c0c'
symbol = '󰚌 '
disabled = false

[directory]
style = "fg:#4c4f69 bg:#c9cbff"
before_repo_root_style = "fg:#4c4f69 bg:#c9cbff"
repo_root_style="fg:#4c4f69 bg:#c9cbff"
read_only= "🔐"
read_only_style= "bg:#f38ba8"
format = "[$path]($style)[$read_only]($read_only_style)"
repo_root_format="[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path  ]($style)[$read_only]($read_only_style)"
truncation_length = 6
truncation_symbol = "…/"
truncate_to_repo = false

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰽰 "
"Pictures" = " "


[git_branch]
symbol = "󰘬"
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#c9cbff bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#c9cbff bg:#394260)]($style)'
#added by me
conflicted = ' 🏳 '
ahead = '🏎💨⇡${count}'
behind = '😰⇣${count}'
diverged = '😵⇕⇡${ahead_count}⇣${behind_count}'
up_to_date = '✓'
untracked = ' 🤷 '
stashed = ' 📦 '
modified = ' 📝 '
staged = '[++\($count\)](green)'
renamed = ' 👅 '
deleted = ' 🗑 '

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#c9cbff bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#c9cbff bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#c9cbff bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#c9cbff bg:#212736)]($style)'

[time]
disabled = false
time_format = "%A %d %b %I:%M %P" # Hour:Minute Format
style = "bg:#6c7086"
format = '[[  $time ](fg:#a0a9cb bg:#6c7086)]($style)'

[status]
style = 'fg:#4c4f69 bg:#c9cbff'
symbol = ''
success_symbol = ''
format = '[ $symbol $common_meaning$signal_name$maybe_int]($style)'
map_symbol = true
disabled = false
