[colors]
ansi = [
    '{{ colors.surface.default.hex }}',
    '{{ colors.error.default.hex }}',
    '{{ colors.primary.default.hex }}',
    '{{ colors.tertiary.default.hex }}',
    '{{ colors.on_primary_container.default.hex }}',
    '{{ colors.on_secondary_container.default.hex }}',
    '{{ colors.primary.default.hex }}',
    '{{ colors.on_surface.default.hex }}',
]
brights = [
    '{{ colors.on_surface_variant.default.hex }}',
    '{{ colors.error.default.hex }}',
    '{{ colors.primary.default.hex }}',
    '{{ colors.tertiary.default.hex }}',
    '{{ colors.on_primary_container.default.hex }}',
    '{{ colors.on_secondary_container.default.hex }}',
    '{{ colors.primary.default.hex }}',
    '{{ colors.on_surface.default.hex }}',
]
cursor_bg = '{{ colors.on_surface.default.hex }}'
cursor_border = '{{ colors.on_surface.default.hex }}'
cursor_fg = '{{ colors.surface.default.hex }}'
foreground = '{{ colors.on_surface.default.hex }}'
background = '{{ colors.surface.default.hex }}'
selection_bg = '{{ colors.primary.default.hex }}'
selection_fg = '{{ colors.on_primary.default.hex }}'

[colors.indexed]

[metadata]
name = 'matugen'

