[[shades]]
name = "vibrance"
default = true

[[shades]]
name = "blue-light-night"
start_time = 17:00:00
end_time = 06:00:00

[[shades]]
name = "blue-light-day"
start_time = 06:00:00
end_time = 17:00:00
