# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

palette = "catppuccin_mocha"


format = """
[░▒▓](overlay0)\
[  ](bg:overlay1 fg:subtext0)\
$sudo\
[](fg:overlay1 bg:surface0)\
$username\
$hostname\
$directory\
[](fg:surface0 bg:overlay2)\
$git_branch\
$git_status\
[](fg:overlay2 bg:surface2)\
$buf\
$bun\
$c\
${custom.cpp}\
${custom.c_sharp}\
$cmake\
$cobol\
$crystal\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$haskell\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$package\
$perl\
$php\
$purescript\
$python\
$raku\
$red\
$rlang\
$ruby\
$rust\
$scala\
$swift\
$typst\
$vagrant\
$vlang\
$zig\
[](fg:surface2 bg:surface0)\
$time\
[](fg:surface0)\
\n$character\
"""

add_newline = false
continuation_prompt = '[❯❯](rosewater)'

[character]
success_symbol = '[❯](green)'
error_symbol = '[❯](red)'

[sudo]
format = '[$symbol]($style)'
style = 'bg:#a6adc8 fg:#1e1e2e'
symbol = '󰚌 '
disabled = false

[username]
style_user = 'fg:lavender bg:surface0'
style_root = 'black bold'
format = '[$user]($style)'
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue)[@$hostname:](fg:lavender bg:surface0)'
trim_at = '.'
ssh_symbol = '󰣀'
disabled = false

[directory]
style = "fg:lavender bg:surface0"
before_repo_root_style = "fg:lavender bg:surface0"
repo_root_style = "fg:lavender bg:surface0"
read_only = " 󰉑 "
read_only_style = "bg:surface0 fg:lavender"
format = "[$path]($style)[$read_only]($read_only_style)"
repo_root_format = "[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path  ]($style)[$read_only]($read_only_style)"
truncation_length = 6
truncation_symbol = "…/"
truncate_to_repo = false

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰽰 "
"Pictures" = " "


[git_branch]
symbol = "󰘬"
style = "bg:overlay2"
format = '[[ $symbol $branch ](fg:#45475a bg:overlay2)]($style)'

[git_status]
style = "bg:overlay2"
format = '[[($all_status$ahead_behind )](fg:#45475a bg:overlay2)]($style)'
#added by me
conflicted = ' 🏳 '
ahead = '󰵵🏎 ⇡${count}'
behind = '󰱬 ⇣${count}'
diverged = '󰚛 ⇕⇡${ahead_count}⇣${behind_count}'
up_to_date = ' ✓ '
untracked = '  '
stashed = ' 📦 '
modified = ' 󰷉 '
staged = '[++\($count\)](fg:#45475a bg:overlay2)'
renamed = ' 󰇹 '
deleted = ' 🗑 '

[time]
disabled = false
time_format = "%A %d %b %I:%M %P "                    # Hour:Minute Format
style = "bg:surface0"
format = '[[ $time](fg:#a6adc8 bg:surface0)]($style)'

[status]
style = 'fg: bg:#1e1e2e'
symbol = ''
success_symbol = ''
format = '[ $symbol $common_meaning$signal_name$maybe_int]($style)'
map_symbol = true
disabled = false

[nodejs]
symbol = ""
style = "bg:surface2"
format = '[[ $symbol ($version) ](fg:#f5e0dc bg:surface2)]($style)'

[rust]
symbol = ""
style = "bg:surface2"
format = '[[ $symbol ($version) ](fg:#f5e0dc bg:surface2)]($style)'

[golang]
symbol = ""
style = "bg:surface2"
format = '[[ $symbol ($version) ](fg:#f5e0dc bg:surface2)]($style)'

[php]
symbol = ""
style = "bg:surface2"
format = '[[ $symbol ($version) ](fg:#f5e0dc bg:surface2)]($style)'

[buf]
symbol = "buf"
style = "bg:surface2"
format = '[[ $symbol ($version) ](fg:#f5e0dc bg:surface2)]($style)'

[bun]
symbol = "󰳯 "
style = "bg:surface2"
format = '[[ $symbol ($version) ](fg:#f5e0dc bg:surface2)]($style)'

[c]
symbol = "󰙱 "
style = "bg:surface2"
format = '[[ $symbol ($version) ](fg:#f5e0dc bg:surface2)]($style)'

[custom.cpp]
disabled = false
symbol = ""
extensions = ["cpp"]
style = "bg:surface2"
command = 'cpp --version | head -n 1 | grep -oP "\d+\.\d+\.\d+"'
format = '[[ $symbol ($output) ](fg:#f5e0dc bg:surface2)]($style)'

[custom.c_sharp]
disabled = false
symbol = " "
extensions = ["cs"]
style = "bg:surface2"
command = 'csc --version | head -n 1 | grep -oP "\d+\.\d+\.\d+"'
format = '[[ $symbol ($version) ](fg:#f5e0dc bg:surface2)]($style)'

[cmake]
symbol = "cmake"
style = "bg:surface2"
format = '[[ $symbol ($version) ](fg:#f5e0dc bg:surface2)]($style)'

[cobol]
symbol = "COBOL"
style = "bg:surface2"
format = '[[ $symbol ($version) ](fg:#f5e0dc bg:surface2)]($style)'

[crystal]
symbol = ""
style = "bg:surface2"
format = '[[ $symbol ($version) ](fg:#f5e0dc bg:surface2)]($style)'

[daml]
symbol = " daml"
style = "bg:surface2"
format = '[[ $symbol ($version) ](fg:#f5e0dc bg:surface2)]($style)'

[dart]
symbol = ""
style = "bg:surface2"
format = '[[ $symbol ($version) ](fg:#f5e0dc bg:surface2)]($style)'

[deno]
symbol = "deno"
style = "bg:surface2"
format = '[[ $symbol ($version) ](fg:#f5e0dc bg:surface2)]($style)'

[dotnet]
symbol = ""
style = "bg:surface2"
format = '[[ $symbol ($version) ](fg:#f5e0dc bg:surface2)]($style)'

[elixir]
symbol = ""
style = "bg:surface2"
format = '[[ $symbol ($version) ](fg:#f5e0dc bg:surface2)]($style)'

[elm]
symbol = ""
style = "bg:surface2"
format = '[[ $symbol ($version) ](fg:#f5e0dc bg:surface2)]($style)'

[erlang]
symbol = ""
style = "bg:surface2"
format = '[[ $symbol ($version) ](fg:#f5e0dc bg:surface2)]($style)'

[fennel]
symbol = ""
style = "bg:surface2"
format = '[[ $symbol ($version) ](fg:#f5e0dc bg:surface2)]($style)'

[haskell]
symbol = ""
style = "bg:surface2"
format = '[[ $symbol ($version) ](fg:#f5e0dc bg:surface2)]($style)'

[helm]
symbol = "󰠳 helm"
style = "bg:surface2"
format = '[[ $symbol ($version) ](fg:#f5e0dc bg:surface2)]($style)'

[java]
symbol = "󰬷"
style = "bg:surface2"
format = '[[ $symbol ($version) ](fg:#f5e0dc bg:surface2)]($style)'

[julia]
symbol = ""
style = "bg:surface2"
format = '[[ $symbol ($version) ](fg:#f5e0dc bg:surface2)]($style)'

[kotlin]
symbol = ""
style = "bg:surface2"
format = '[[ $symbol ($version) ](fg:#f5e0dc bg:surface2)]($style)'

[lua]
symbol = "󰢱"
style = "bg:surface2"
format = '[[ $symbol ($version) ](fg:#f5e0dc bg:surface2)]($style)'

[nim]
symbol = ""
style = "bg:surface2"
format = '[[ $symbol ($version) ](fg:#f5e0dc bg:surface2)]($style)'

[ocaml]
symbol = ""
style = "bg:surface2"
format = '[[ $symbol ($version) ](fg:#f5e0dc bg:surface2)]($style)'

[opa]
symbol = "󰵰"
style = "bg:surface2"
format = '[[ $symbol ($version) ](fg:#f5e0dc bg:surface2)]($style)'

[package]
symbol = ""
style = "bg:surface2"
format = '[[ $symbol ($version) ](fg:#f5e0dc bg:surface2)]($style)'

[perl]
symbol = ""
style = "bg:surface2"
format = '[[ $symbol ($version) ](fg:#f5e0dc bg:surface2)]($style)'

[purescript]
symbol = ""
style = "bg:surface2"
format = '[[ $symbol ($version) ](fg:#f5e0dc bg:surface2)]($style)'

[python]
symbol = ""
style = "bg:surface2"
format = '[[ $symbol ($version) ](fg:#f5e0dc bg:surface2)]($style)'

[raku]
symbol = ""
style = "bg:surface2"
format = '[[ $symbol ($version) ](fg:#f5e0dc bg:surface2)]($style)'

[red]
symbol = "󱥒 red"
style = "bg:surface2"
format = '[[ $symbol ($version) ](fg:#f5e0dc bg:surface2)]($style)'

[rlang]
symbol = "rlang"
style = "bg:surface2"
format = '[[ $symbol ($version) ](fg:#f5e0dc bg:surface2)]($style)'

[ruby]
symbol = ""
style = "bg:surface2"
format = '[[ $symbol ($version) ](fg:#f5e0dc bg:surface2)]($style)'

[scala]
symbol = ""
style = "bg:surface2"
format = '[[ $symbol ($version) ](fg:#f5e0dc bg:surface2)]($style)'

[swift]
symbol = ""
style = "bg:surface2"
format = '[[ $symbol ($version) ](fg:#f5e0dc bg:surface2)]($style)'

[typst]
symbol = "typst"
style = "bg:surface2"
format = '[[ $symbol ($version) ](fg:#f5e0dc bg:surface2)]($style)'

[vagrant]
symbol = " vagrant"
style = "bg:surface2"
format = '[[ $symbol ($version) ](fg:#f5e0dc bg:surface2)]($style)'

[vlang]
symbol = ""
style = "bg:surface2"
format = '[[ $symbol ($version) ](fg:#f5e0dc bg:surface2)]($style)'

[zig]
symbol = ""
style = "bg:surface2"
format = '[[ $symbol ($version) ](fg:#f5e0dc bg:surface2)]($style)'


# Palette definitions
[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "surface0"
crust = "#11111b"
