[templates.ags]
input_path = '~/.config/matugen/templates/ags.scss'
output_path = '~/.config/ags/scss/colors.scss'
mode = "Dark"

[templates.legacy]
input_path = '~/.config/matugen/templates/legacy'
output_path = '~/.cache/current_wall_path.txt'
mode = "Dark"

[templates.legacy1]
input_path = '~/.config/matugen/templates/colors.sh'
output_path = '~/.cache/matugen/colors.sh'
mode = "Dark"

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-4.0/colors.css'
mode = "Dark"

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-3.0/colors.css'
mode = "Dark"

[templates.qt_oomox]
input_path = '~/.config/matugen/templates/qt-oomox-styleplugin'
output_path = '~/.config/oomox-qtstyleplugin/themes/matugen.css'
mode = "Dark"

[templates.kdeglobals]
input_path = '~/.config/matugen/templates/kdeglobals.conf'
output_path = '~/.config/kdeglobals'
mode = "Dark"

[templates.hypr]
input_path = '~/.config/matugen/templates/hypr.conf'
output_path = '~/.cache/matugen/hyprland-colors.conf'
mode = "Dark"

#[templates.river]
#input_path = '~/.config/matugen/templates/river.sh'
#output_path = '~/.config/river/colors.sh'
#mode = "Dark"

[templates.wezterm]
input_path = '~/.config/matugen/templates/wezterm.toml'
output_path = '~/.config/wezterm/colors/matugen.toml'
mode = "Dark"



[config]
reload_apps = false
set_wallpaper = true
wallpaper_tool = 'Swww'
swww_options = [
    "--transition-step",
    "10",
    "--transition-fps",
    "90",
    "--transition-type",
    "random",
    "--transition-duration",
    "1.0",
]

